### ISSUE TITLE
Recompilation in an editable install hides all compiler output

### ISSUE THREAD

**Issue by Cadair** [mesonbuild/meson-python#820]
This line:

https://github.com/mesonbuild/meson-python/blob/8e985984f9044a467b226772486c140cf9b3b467/mesonpy/_editable.py#L346

hides all build output, so if the build fails due to missing build requirements or some other reason, you don't get any indication as to why.

I would expect the compilation output to be shown at import time.

I found this while trying to do an editable install of numpy, and because the initial install of numpy used build isolation the import time recompile did not have the build requirements (cython).

**Comment by rgommers** [comment]
Does https://mesonbuild.com/meson-python/how-to-guides/editable-installs.html#verbose-mode help?

There might be an improvement to make there, showing the build output by default only if the build fails.

**Comment by orlitzky** [comment]
We've received a lot of complaints about this since switching to meson-python (with an editable install by default) in SageMath. Sage is a big project, so touching the wrong file can lead to a mysterious hour-long delay when you go to test your changes.

**Comment by dimpase** [comment]
As far as I understand, it's currently not possible to pass `-Ceditable-verbose=yes` via `meson.options`.
Although it would be useful...

**Comment by eli-schwartz** [comment]
> As far as I understand, it's currently not possible to pass `-Ceditable-verbose=yes` via `meson.options`. Although it would be useful...

That file is solely used to define new options (and their default values) that don't previously exist; it cannot pass values for any existing options. The project `default_options` can be used to pass values for any built-in meson option (but not pep517 build backend options owned by meson-python).

Meson-python as it stands today is primarily configured via pyproject.toml

(Editable-verbose is not listed as available to be set via https://mesonbuild.com/meson-python/reference/pyproject-settings.html however.)

**Comment by dimpase** [comment]
> Editable-verbose is not listed as available

why can't it be set in the project (meta)data, be it in `pyproject.toml`, or in `menson.build`, or in `meson.options` ?

Looks like a bug to me. We don't want to tell the users to normally/always use a non-default option, or always have an environment variable set. Normal operations should be working out of the box.

**Comment by dnicolodi** [comment]
No one ever asked for it. But it can be added. See #838

**Comment by rgommers** [comment]
A setting in pyproject.toml to change the default behavior is no merged (gh-838) and will be released very soon in 0.21.0. A mode to only show the relevant part of a build error on failure by default, and be silent otherwise, still has an open PR: gh-750.

**Comment by dnicolodi** [comment]
#750 started out on the wrong foot and is still wrong. The author seems to have lost interest in fixing it.

**Comment by rgommers** [comment]
The principle discussed there is still valid though: parse the ninja logs and show the relevant part of a build failure. Hence why this issue is still open. In case gh-750 keeps being stalled, someone else can give that a go.
